
//! Synthetic TypeScript module generator for wundler benchmarks.
//!
//! Produces N realistic `.tsx` files that exercise the full wundler pipeline:
//! static imports, dynamic imports, interfaces, classes, exported functions,
//! and (for every 20th module) a top-level side effect detected as
//! `SideEffectMarker::Definite`.

use std::collections::BTreeSet;
use std::fs;

use anyhow::{Context, Result};
use tempfile::TempDir;

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/// A freshly-generated synthetic TypeScript application in a temporary directory.
///
/// The directory is automatically removed when this struct is dropped.
pub struct SyntheticApp {
    /// Temporary directory containing the generated source files.
    pub dir: TempDir,
    /// Number of modules (`src/mod_NNNNN.tsx`) generated.
    pub n_modules: usize,
}

impl SyntheticApp {
    /// Generate `n_modules` synthetic TypeScript modules (plus `main.tsx` and a
    /// `wundler.toml`) **directly into `dest`**, without a temporary directory.
    ///
    /// `dest` is created if it does not exist.  Files are written straight to
    /// `<dest>/src/` so the directory persists after this call returns.  A
    /// `wundler.toml` is also emitted so the result is immediately usable with
    /// `wundler analyze <dest>/src --entry /=<dest>/src/main.tsx`.
    ///
    /// # Errors
    /// Returns an error if any file I/O fails.
    pub fn generate_at(n_modules: usize, dest: &std::path::Path) -> Result<()> {
        let src = dest.join("src");
        fs::create_dir_all(&src).context("failed to create dest/src/")?;

        let nonce = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);

        for i in 0..n_modules {
            let content = generate_module(i, n_modules, nonce);
            fs::write(src.join(format!("mod_{:05}.tsx", i)), &content)
                .with_context(|| format!("failed to write mod_{:05}.tsx", i))?;
        }

        let main_content = generate_main(n_modules, nonce);
        fs::write(src.join("main.tsx"), &main_content)
            .context("failed to write main.tsx")?;

        // wundler.toml — mirrors the test-app convention so `wundler analyze`
        // can be invoked against this directory without extra flags.
        let toml = format!(
            "# Auto-generated by wundler-bench (SyntheticApp, N={})\n\
             [build]\n\
             root = \"src\"\n\
             out_dir = \"dist\"\n\
             engine = \"swc\"\n\
             source_maps = false\n\
             commons_threshold = 2\n\
             \n\
             [entry]\n\
             \"/\" = \"src/main.tsx\"\n",
            n_modules
        );
        fs::write(dest.join("wundler.toml"), toml)
            .context("failed to write wundler.toml")?;

        Ok(())
    }

    /// Create `n_modules` synthetic TypeScript modules plus a `main.tsx` entry
    /// point in a fresh temporary directory.
    ///
    /// Each call generates a **unique nonce** embedded in every module's content
    /// so that different `SyntheticApp` instances have distinct content hashes —
    /// ensuring that cold-build timing measurements see true cache misses while
    /// warm-build measurements (on the same instance after touching one module)
    /// see genuine cache hits for the unchanged modules.
    ///
    /// File layout:
    /// ```text
    /// <temp_dir>/
    ///   src/
    ///     mod_00000.tsx   ← shared utility (imported by everyone)
    ///     mod_00001.tsx
    ///     …
    ///     mod_NNNNN.tsx
    ///     main.tsx        ← entry point with static + dynamic imports
    /// ```
    pub fn generate(n_modules: usize) -> Result<Self> {
        let dir = TempDir::new().context("failed to create temp dir")?;
        let src = dir.path().join("src");
        fs::create_dir_all(&src).context("failed to create src/")?;

        // Unique nonce per generate() call — guarantees distinct content hashes.
        let nonce = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);

        for i in 0..n_modules {
            let content = generate_module(i, n_modules, nonce);
            fs::write(src.join(format!("mod_{:05}.tsx", i)), &content)
                .with_context(|| format!("failed to write mod_{:05}.tsx", i))?;
        }

        let main_content = generate_main(n_modules, nonce);
        fs::write(src.join("main.tsx"), &main_content)
            .context("failed to write main.tsx")?;

        Ok(SyntheticApp { dir, n_modules })
    }

    /// Update module `i`'s source, changing its content hash.
    ///
    /// Increments the `__BENCH_VERSION__` marker embedded in each module, which
    /// produces a new `ContentHash` without invalidating neighbouring modules.
    pub fn touch_module(&self, i: usize) -> Result<()> {
        let path = self
            .dir
            .path()
            .join("src")
            .join(format!("mod_{:05}.tsx", i));
        let content = fs::read_to_string(&path)
            .with_context(|| format!("touch_module: failed to read mod_{:05}.tsx", i))?;

        let updated = bump_bench_version(&content);
        fs::write(&path, updated)
            .with_context(|| format!("touch_module: failed to write mod_{:05}.tsx", i))?;
        Ok(())
    }

    /// Touch the last `floor(n_modules * fraction)` modules (minimum 1).
    ///
    /// Targets the high-numbered modules (which reside in lazy chunks under the
    /// synthetic dependency structure), demonstrating that ABS savings are
    /// proportional to chunk-level churn, not module-level churn.
    ///
    /// Returns the list of module indices that were touched.
    pub fn churn(&self, fraction: f64) -> Result<Vec<usize>> {
        let n_change = ((self.n_modules as f64 * fraction).round() as usize).max(1);
        let n_change = n_change.min(self.n_modules);
        let start = self.n_modules.saturating_sub(n_change);
        let indices: Vec<usize> = (start..self.n_modules).collect();
        for &idx in &indices {
            self.touch_module(idx)?;
        }
        Ok(indices)
    }
}

// ---------------------------------------------------------------------------
// Module content generators
// ---------------------------------------------------------------------------

/// Determine the deduplicated set of module indices that module `i` imports.
///
/// Rules (from the benchmark spec):
/// - Always import `mod_00000` (shared utility / commons candidate).
/// - Import `mod_{i-1}` if `i > 0`.
/// - Import `mod_{i-7}` if `i >= 7` (and it differs from the others).
/// - Never self-import.
fn import_deps(i: usize) -> Vec<usize> {
    let mut deps: BTreeSet<usize> = BTreeSet::new();
    deps.insert(0); // shared utility
    if i > 0 {
        deps.insert(i - 1);
    }
    if i >= 7 {
        deps.insert(i - 7);
    }
    deps.remove(&i); // no self-import
    deps.into_iter().collect()
}

/// Generate the TypeScript source for module `i`.
fn generate_module(i: usize, _n_modules: usize, nonce: u128) -> String {
    let deps = import_deps(i);

    let mut lines: Vec<String> = Vec::new();

    // ------------------------------------------------------------------
    // Unique nonce ensures distinct content hashes across generate() calls
    // Version marker used by touch_module to bump the content hash
    // ------------------------------------------------------------------
    lines.push(format!("// __BENCH_NONCE__ = {}  __BENCH_VERSION__ = 0  (module {:05})", nonce, i));

    // ------------------------------------------------------------------
    // Import statements
    // ------------------------------------------------------------------
    for &dep in &deps {
        if dep == 0 && i != 0 {
            lines.push(format!(
                "import {{ process_{:05}, compute_{:05}, SharedService{:05} }} from './mod_{:05}';",
                dep, dep, dep, dep
            ));
        } else if dep != i {
            lines.push(format!(
                "import {{ process_{:05}, compute_{:05} }} from './mod_{:05}';",
                dep, dep, dep
            ));
        }
    }
    // Every module nominally imports React (common in React codebases).
    // The graph resolver silently drops bare-specifier imports (no file to match).
    lines.push("import React from 'react';".to_string());
    lines.push(String::new());

    // ------------------------------------------------------------------
    // Interface declarations
    // ------------------------------------------------------------------
    lines.push(format!("export interface Config{:05} {{", i));
    lines.push("  value: number;".to_string());
    lines.push("  label: string;".to_string());
    lines.push("  enabled: boolean;".to_string());
    lines.push("}".to_string());
    lines.push(String::new());
    lines.push(format!("export interface Result{:05} {{", i));
    lines.push("  output: string;".to_string());
    lines.push("  timestamp: number;".to_string());
    lines.push("}".to_string());
    lines.push(String::new());

    // ------------------------------------------------------------------
    // ALIVE export: process_NNNNN
    // ------------------------------------------------------------------
    lines.push(format!(
        "export function process_{:05}(cfg: Config{:05}): Result{:05} {{",
        i, i, i
    ));
    if i == 0 {
        lines.push("  const doubled = cfg.value * 2;".to_string());
        lines.push(format!(
            "  return {{ output: `result_${{doubled}}_{:05}`, timestamp: Date.now() }};",
            i
        ));
    } else {
        for (idx, &dep) in deps.iter().enumerate() {
            if dep != i {
                lines.push(format!(
                    "  const _r{} = process_{:05}({{ value: cfg.value + {}, label: cfg.label, enabled: cfg.enabled }});",
                    idx, dep, idx
                ));
            }
        }
        lines.push(format!(
            "  return {{ output: `${{_r0?.output ?? ''}}_{:05}`, timestamp: Date.now() }};",
            i
        ));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    // ------------------------------------------------------------------
    // ALIVE export: compute_NNNNN
    // ------------------------------------------------------------------
    lines.push(format!(
        "export function compute_{:05}(val: boolean): string {{",
        i
    ));
    if i == 0 {
        lines.push(format!(
            "  return val ? 'active_{:05}' : 'inactive_{:05}';",
            i, i
        ));
    } else {
        let first_dep = deps.first().copied().unwrap_or(0);
        lines.push(format!("  const base = compute_{:05}(val);", first_dep));
        lines.push(format!(
            "  return val ? `active_${{base}}_{:05}` : `inactive_${{base}}_{:05}`;",
            i, i
        ));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    // ------------------------------------------------------------------
    // Constants
    // ------------------------------------------------------------------
    lines.push(format!("export const MODULE_ID_{:05} = {};", i, i));
    lines.push(format!(
        "export const MODULE_LABEL_{:05} = 'module-{:05}';",
        i, i
    ));
    lines.push(String::new());

    // ------------------------------------------------------------------
    // Class (adds realistic bulk to the module)
    // ------------------------------------------------------------------
    if i == 0 {
        lines.push(format!("export class SharedService{:05} {{", i));
        lines.push("  private readonly id: number;".to_string());
        lines.push("  constructor(id: number) { this.id = id; }".to_string());
        lines.push(format!(
            "  run(cfg: Config{:05}): Result{:05} {{ return process_{:05}(cfg); }}",
            i, i, i
        ));
        lines.push("}".to_string());
        lines.push(String::new());
    } else {
        lines.push(format!("export class Service{:05} {{", i));
        lines.push("  private svc: SharedService00000;".to_string());
        lines.push(format!(
            "  constructor() {{ this.svc = new SharedService00000({}); }}",
            i
        ));
        lines.push(format!(
            "  run(cfg: Config{:05}): Result{:05} {{ return process_{:05}(cfg); }}",
            i, i, i
        ));
        lines.push("}".to_string());
        lines.push(String::new());
    }

    // ------------------------------------------------------------------
    // DEAD export: every 5th module
    // ------------------------------------------------------------------
    if i % 5 == 0 && i != 0 {
        lines.push(
            "// DEAD export — never imported by anyone (dead-code-elimination candidate)."
                .to_string(),
        );
        lines.push(format!("export function unused_{:05}(): void {{}}", i));
        lines.push(String::new());
    }

    // ------------------------------------------------------------------
    // SIDE EFFECT: every 20th module (detected as DEFINITE by the analyser)
    // ------------------------------------------------------------------
    if i % 20 == 0 && i != 0 {
        lines.push(
            "// SIDE EFFECT — writes to ambient global (SideEffectMarker::Definite).".to_string(),
        );
        lines.push(format!("window.__wundler_bench_{:05} = true;", i));
        lines.push(String::new());
    }

    // ------------------------------------------------------------------
    // Module-level type alias
    // ------------------------------------------------------------------
    lines.push(format!(
        "export type ModuleMap{:05} = Record<string, Config{:05}>;",
        i, i
    ));

    lines.join("\n") + "\n"
}

/// Generate the entry-point `main.tsx`.
///
/// Statically imports `mod_00000` through `mod_00003`, and dynamically imports
/// `mod_{n_modules/2}` and `mod_{n_modules-1}` to create lazy chunk boundaries.
fn generate_main(n_modules: usize, nonce: u128) -> String {
    let half = (n_modules / 2).max(1).min(n_modules.saturating_sub(1));
    let last = n_modules.saturating_sub(1);

    let mut lines: Vec<String> = Vec::new();

    lines.push(format!("// __BENCH_NONCE__ = {}  __BENCH_VERSION__ = 0  (main entry point)", nonce));
    lines.push(String::new());

    // Static imports
    let static_count = 4.min(n_modules);
    for i in 0..static_count {
        lines.push(format!(
            "import {{ process_{:05}, compute_{:05} }} from './mod_{:05}';",
            i, i, i
        ));
    }
    lines.push("import React from 'react';".to_string());
    lines.push(String::new());

    // Main function (uses the statically imported modules)
    lines.push("export function main(): void {".to_string());
    for i in 0..static_count {
        lines.push(format!(
            "  const _r{0} = process_{1:05}({{ value: {0}, label: 'bench', enabled: true }});",
            i, i
        ));
        lines.push(format!("  const _c{0} = compute_{1:05}(true);", i, i));
        lines.push(format!("  console.log(_r{}, _c{});", i, i));
    }
    lines.push("}".to_string());
    lines.push(String::new());

    // Dynamic imports — create lazy chunk boundaries
    if half > 0 && half < n_modules {
        lines.push(format!(
            "// Dynamic import: lazy chunk at module {:05}",
            half
        ));
        lines.push(format!(
            "const loadHalf = (): Promise<any> => import('./mod_{:05}');",
            half
        ));
    }
    if last != half && last > 0 {
        lines.push(format!(
            "// Dynamic import: lazy chunk at module {:05}",
            last
        ));
        lines.push(format!(
            "const loadLast = (): Promise<any> => import('./mod_{:05}');",
            last
        ));
    }
    lines.push(String::new());

    // Export the loaders so they aren't dead code
    lines.push("export { loadHalf, loadLast };".to_string());
    lines.push(String::new());
    lines.push("main();".to_string());

    lines.join("\n") + "\n"
}

// ---------------------------------------------------------------------------
// Version bumping helper
// ---------------------------------------------------------------------------

/// Increment the `__BENCH_VERSION__ = N` marker in `content` by 1.
///
/// The marker may appear anywhere in a line (e.g. embedded after the nonce).
/// If no marker is found, appends a new `// __BENCH_VERSION__ = 1` line.
pub(crate) fn bump_bench_version(content: &str) -> String {
    const MARKER: &str = "__BENCH_VERSION__ = ";
    if let Some(pos) = content.find(MARKER) {
        let rest_start = pos + MARKER.len();
        // Find the end of the version number (digits only)
        let end = content[rest_start..]
            .find(|c: char| !c.is_ascii_digit())
            .map(|offset| rest_start + offset)
            .unwrap_or(content.len());
        let version_str = &content[rest_start..end];
        let version: u64 = version_str.parse().unwrap_or(0);
        format!(
            "{}{}{}",
            &content[..rest_start],
            version + 1,
            &content[end..]
        )
    } else {
        // Append a version marker if none exists
        format!("{}\n// __BENCH_VERSION__ = {}\n", content, 1)
    }
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bump_increments_version() {
        let src = "// __BENCH_VERSION__ = 0\nexport const x = 1;\n";
        let bumped = bump_bench_version(src);
        assert!(bumped.contains("// __BENCH_VERSION__ = 1"));
    }

    #[test]
    fn bump_twice() {
        let src = "// __BENCH_VERSION__ = 0\n";
        let once = bump_bench_version(src);
        let twice = bump_bench_version(&once);
        assert!(twice.contains("// __BENCH_VERSION__ = 2"));
    }

    #[test]
    fn import_deps_mod0() {
        // Module 0 imports nothing (self-import filtered, no i-1 since i==0)
        let deps = import_deps(0);
        assert!(deps.is_empty(), "mod_00000 should have no deps: {:?}", deps);
    }

    #[test]
    fn import_deps_mod1() {
        // Module 1: shared_util=0 (same as i-1=0), deduplicated → [0]
        let deps = import_deps(1);
        assert_eq!(deps, vec![0]);
    }

    #[test]
    fn import_deps_mod8() {
        // Module 8: deps are [i-1=7, i-7=1, shared_util=0] = [0, 1, 7]
        let mut deps = import_deps(8);
        deps.sort();
        assert_eq!(deps, vec![0, 1, 7]);
    }
}
