[package]
name = "wundler-dev"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
blake3 = "1"
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = "3"
tracing = "0.1"
walkdir = "2"

[dev-dependencies]
tempfile = "3"
